In [55]:
import numpy as np

In [56]:
x = [
  [
    [15, -2, 1],
    [3, 12, -4],
    [2, -1, 10]
  ],

  [
    [4, 7, -2],
    [6, 5, 3],
    [1, -8, 4]
  ],

  [
    [14, -2, 1, 3],
    [2, 11, -4, 1],
    [1, -3, 12, 2],
    [3, 1, -2, 13]
  ],

  [
    [5, -4, 3, 2],
    [7, 6, -5, 1],
    [2, 8, 4, -3],
    [1, 2, 6, 5]
  ],

  [
    [18, 4, -2],
    [3, 16, 1],
    [2, -3, 14]
  ],

  [
    [3, 5, -4],
    [7, 2, 6],
    [4, -8, 3]
  ],

  [
    [20, -3, 2, 1],
    [4, 18, -2, 3],
    [1, -4, 17, 2],
    [2, 3, -1, 16]
  ]
];

y = [
  [28, 35, 19],
  [17, 24, -8],
  [45, 31, 28, 39],
  [22, 14, 18, 27],
  [56, 48, 31],
  [12, 25, -17],
  [64, 52, 47, 38]
];

In [57]:
def not_diagonally_dominance(A):
    diag = np.diag(np.abs(A))
    off_diag = np.sum(np.abs(A), axis=1) - diag
                            #axis 1 itu ambil yang di satu row yang sama
                            #axis 0 itu ambil satu col
                        
    
    if np.all(diag > off_diag):
        return False
        print("Tidak diagonal Dominance")
    else:
        print("Diagonal Dominance")
        return True

In [58]:
def gauss_seidel(x,y, max_iters = 53, tol = 0.035):
    
    xs = np.array(x)
    ys = np.array(y)
    
    if (not_diagonally_dominance(xs)):
        return
    
    diag = np.diag(xs)
    x_old = np.zeros(xs.shape[0])
    
    xs = -xs
    np.fill_diagonal(xs, 0)
    
    for i in range(max_iters):
        
        x_new = np.array(x_old)
        
            #J buat index
        for j, row in enumerate(xs):
            x_new[j] = (ys[j] + np.dot(row, x_new)) / diag[j]
            #j = 1, index ke 1
            # row itu koefisien per baris
            
        print(x_new)
        error = np.sqrt(np.sum((x_new-x_old)**2))
        # print(error)
        if (error < tol):
            print("Konvergen")
            print(f"Penyelesaian x = {x_new} dengan error = {error}") #5 angka belakang koma
            return x_new
        
        x_old = x_new


In [59]:
def main():
    for idx, (Matrix_A, Matrix_B) in enumerate(zip(x, y)):
        hasil = gauss_seidel(Matrix_A, Matrix_B)
        

In [60]:
main()

[1.86666667 2.45       1.77166667]
[2.07522222 2.98841667 1.78379722]
[2.14620241 2.97471514 1.76823103]
[2.14541328 2.96972369 1.76788971]
Konvergen
Penyelesaian x = [2.14541328 2.96972369 1.76788971] dengan error = 0.005064955891938789
Diagonal Dominance
[3.21428571 2.23376623 2.62391775 2.49009324]
[2.81238107 3.0346196  2.4426076  2.49334249]
[2.93904315 2.94536378 2.40919693 2.46583851]
[2.93457251 2.93652766 2.41194445 2.46797259]
Konvergen
Penyelesaian x = [2.93457251 2.93652766 2.41194445 2.46797259] dengan error = 0.010496046582956994
Diagonal Dominance
[3.11111111 2.41666667 2.28769841]
[2.82826279 2.32671958 2.30883094]
[2.85059909 2.32121074 2.30445957]
Konvergen
Penyelesaian x = [2.85059909 2.32121074 2.30445957] dengan error = 0.023417226162003705
Diagonal Dominance
[3.2        2.17777778 3.08888889 1.75972222]
[3.12979167 2.24330247 2.90141022 1.74449497]
[3.1591296  2.21848984 2.89563764 1.74511931]
[3.15595375 2.21845013 2.89574166 1.74553024]
Konvergen
Penyelesaian x 