In [6]:


x = [
    [
        [95, 12, -8],
        [7, -88, 14],
        [5, 9, -102]
    ],
    [
        [120, -15, 10],
        [8, -110, 6],
        [12, 7, -98]
    ],
    [
        [-105, 18, 9],
        [6, -92, 11],
        [10, 5, -115]
    ],
    [
        [85, -6, 4],
        [3, 97, 8],
        [7, 2, 90]
    ],
    [
        [-130, 25, 12],
        [14, -140, 20],
        [18, 10, -150]
    ]
]

y = [
    [210, -340, 415],
    [-520, 630, -710],
    [305, -450, 520],
    [150, 275, 390],
    [-610, 720, -830]
]
import numpy as np

def is_not_diagonally_dominance(A):
    diag = np.diag(np.abs(A))
    off_diag = np.sum(np.abs(A), axis=1) - diag
    
    if np.all(diag > off_diag):
        return False
    else:
        return True
    
    
def gauss_seidel(matrix_A, matrix_B, max_iters = 53, tolerance = 0.093):
    
    xs = np.array(matrix_A)
    ys = np.array(matrix_B)
    
    if (is_not_diagonally_dominance(xs)):
        print("Not diagonally Dominant")
        return
    
    diag = np.diag(xs)
    xs = -xs
    np.fill_diagonal(xs, 0)
    
    x_old = np.zeros(xs.shape[0])
    
    for iter in range(max_iters):
        
        x_new = np.array(x_old)
        
        for j, row in enumerate(xs):
            x_new[j] = (ys[j] - np.dot(row, x_new)) / diag[j]
            
        print(x_new)
        
        error = np.sqrt(np.sum((x_new - x_old)**2))
        
        if error < tolerance:
            print("Convergent")
            return
        
        x_old = x_new
        
    
def main():
    for idx, (matrix_A, matrix_B) in enumerate(zip(x,y)):
        
        gauss_seidel(matrix_A, matrix_B)
        
main()
        
        


[ 2.21052632  3.68779904 -4.50238062]
[ 3.0555014   4.33687294 -4.60107219]
[ 3.14580056  4.34539099 -4.60625021]
Convergent
[-4.33333333 -5.41212121  8.16209029]
[-2.97664399 -5.95599445  8.03481315]
[-2.91926626 -5.95322499  8.02758949]
Convergent
[-2.9047619   5.08074534 -4.49005311]
[-3.39088513  5.64930321 -4.47250143]
[-3.48985662  5.6536593  -4.46408461]
[-3.49132482  5.65274869 -4.46391735]
Convergent
[1.76470588 2.88963008 4.53480224]
[1.77413445 3.26392599 4.54385326]
[1.7481395  3.2638685  4.54183015]
Convergent
[ 4.69230769 -5.61208791  5.3443956 ]
[ 5.27822654 -6.43416488  5.32889047]
[ 5.43774951 -6.44790216  5.31066354]
[ 5.44207378 -6.44573074  5.30999986]
Convergent
