In [26]:
import numpy as np

x = [ 
    [ 
        [-61, 11, 7], 
        [20, 67, 8], 
        [38, 16, -98] 
    ], 
    [ 
        [-109, 14, 57], 
        [2, -64, 24], 
        [38, 4, -85] 
    ], 
    [ 
        [-62, 3, 13], 
        [17, -93, 39], 
        [20, 8, -69] 
    ], 
    [ 
        [105, 28, 112], 
        [56, 97, 84], 
        [20, 81, -60] 
    ], 
    [ 
        [-87, 23, 23], 
        [11, 95, 45], 
        [18, 44, -108] 
    ] 
] 
 
y = [ 
    [-969, 79, -265], 
    [78, -1, -382], 
    [-970, -849, -449], 
    [198, -314, 193], 
    [882, -17, 945] 
] 

In [27]:
def is_not_diagonally_dominance(A):
    diag = np.diag(np.abs(A))
    off_diag = np.sum(np.abs(A), axis=1) - diag
    
    if np.all(diag >= off_diag):
        return False
    else:
        return True

def gauss_seidel(matrix_A, matrix_B, max_iters=16, tolerance=0.099):
    xs = np.array(matrix_A)
    ys = np.array(matrix_B)
    
    if is_not_diagonally_dominance(xs):
        print("Tidak diagonally dominance")
        return
    
    diag = np.diag(xs)
    xs = -xs
    np.fill_diagonal(xs, 0)
    
    x_old = np.zeros(xs.shape[0])
    
    for iter in range(max_iters):
        
        x_new = np.array(x_old)
        
        for j, row in enumerate(xs):
            x_new[j] = (ys[j] + np.dot(row, x_new))/ diag[j]
            
        print(f"Solusi iterasi ke-{iter}")
        print(x_new)
        
        error = np.sqrt(np.sum((x_new - x_old)**2))
        
        if error < tolerance:
            print("konvergen")
            return
        
        x_old = np.array(x_new)
        
        
def main():
    
    for idx, (matrix_A,matrix_B) in enumerate(zip(x,y)):
        
        print(f"soal ke-{idx}")
        print(matrix_A)
        print(matrix_B)
        gauss_seidel(matrix_A, matrix_B)
        
        
main()  

soal ke-0
[[-61, 11, 7], [20, 67, 8], [38, 16, -98]]
[-969, 79, -265]
Solusi iterasi ke-0
[15.8852459  -3.56275997  8.28199168]
Solusi iterasi ke-1
[16.19317348 -4.64357318  8.22493287]
Solusi iterasi ke-2
[15.991725   -4.57662631  8.1577503 ]
Solusi iterasi ke-3
[15.99608791 -4.56990687  8.16053909]
konvergen
soal ke-1
[[-109, 14, 57], [2, -64, 24], [38, 4, -85]]
[78, -1, -382]
Solusi iterasi ke-0
[-0.71559633 -0.00673739  4.17388694]
Solusi iterasi ke-1
[1.46621314 1.62665176 5.22614949]
Solusi iterasi ke-2
[2.22627198 2.04500206 5.58562757]
Solusi iterasi ke-3
[2.46798899 2.18735999 5.70038849]
Solusi iterasi ke-4
[2.54628609 2.23284212 5.73753223]
konvergen
soal ke-2
[[-62, 3, 13], [17, -93, 39], [20, 8, -69]]
[-970, -849, -449]
Solusi iterasi ke-0
[15.64516129 11.98890045 12.43209318]
Solusi iterasi ke-1
[18.83199859 17.78489903 14.02781397]
Solusi iterasi ke-2
[19.44703675 18.5664986  14.29670614]
Solusi iterasi ke-3
[19.5412367  18.69647918 14.33908069]
Solusi iterasi ke-4
[19.5