In [1]:
x = [ 
    [ 
        [-61, 11, 7], 
        [20, 67, 8], 
        [38, 16, -98] 
    ], 
    [ 
        [-109, 14, 57], 
        [2, -64, 24], 
        [38, 4, -85] 
    ], 
    [ 
        [-62, 3, 13], 
        [17, -93, 39], 
        [20, 8, -69] 
    ], 
    [ 
        [105, 28, 112], 
        [56, 97, 84], 
        [20, 81, -60] 
    ], 
    [ 
        [-87, 23, 23], 
        [11, 95, 45], 
        [18, 44, -108] 
    ] 
] 
 
y = [ 
    [-969, 79, -265], 
    [78, -1, -382], 
    [-970, -849, -449], 
    [198, -314, 193], 
    [882, -17, 945] 
] 

In [2]:
import numpy as np

#buat fungsi cek diagonal dominance dulu

def isNotDiagonallyDominant(A):
        #ubah angka jadi positif semua (Absolut) (di diag domi hanya nilai abs yang di cek)
        #ambil nilai diag nya
    diag = np.diag(np.abs(A))
    print("Matrix diag:")
    print(diag)
    
    print()
    
    #buat var matrix selain diag
        #jumlahkan nilai abs(A) secara horizontal (axis = 1)
        # kurangi dengan diag
    off_diag = np.sum(np.abs(A), axis = 1) - diag
    print("Matrix total offDiag:")
    print(off_diag)
    
    #cek semua element matrixnya, kalau semua diag >= off_diag berarti dia Diag Domi
    if np.all(diag >= off_diag):
        return False #dia diaogally dominace
    else:
        return True #dia TIDAK diagonaly dominance
    
    
    
def gauss_seidel(matrix_A, matrix_B, max_iters = 16, tolerance = 0.099):
    #buat jadi matrix dulu
    xs = np.array(matrix_A)
    ys = np.array(matrix_B)
    
    #cek apakah xs diagonal dominance 
    if (isNotDiagonallyDominant(xs)):
        print("Kaga diagonal Dominance")
        return
    
    #manipulasi koefisien seperti isolasi x di mtk
        #simpan nilai diag untuk pembagian nanti
        #ubah koef jadi negatif (-xs)
        #isi NOL di Koef diagonal
    diag = np.diag(xs)
    xs = -xs
    np.fill_diagonal(xs, 0)
    
    #BUAT TEBAKAN AWAL (Matrix 0 dengan shape 3*3 [xs.shape] baris 1 [0])
    x_old = np.zeros(xs.shape[0])
    
    #lakukan iterasi sampai yang dimau
    for idx  in range(max_iters):
        
        #update nilai x
        x_new = np.array(x_old)
        
        #iterasi solusi gauss seidel
        for j, row in enumerate(xs): #j itu idx dari enumerate, row itu baris dari matrix xs
                #buat x_new dari (b + (= x2*a2 - x3*a3) )/ diag LAKUKAN UNTUK TIAP BARIS
            x_new[j] = (ys[j] + np.dot(row, x_new)) / diag[j]
            
        print(f"Solusi x iterasi ke {idx}")
        print(x_new)
        
        #hitung error untuk toleransi
            #kuadratkan selisih x_new dan x_old
            #jumlah semua selisih tadi
            #akarkan jumlah tersebut
        error = np.sqrt(np.sum((x_new - x_old)**2))
        
        if (error < tolerance):
            print("Sudah Konvergen")
            return
        
        
        x_old = np.array(x_new) # jangan lupa update x_old setiap iterasi
        
            
    
def main():
    for idx, (matrix_A, matrix_B) in enumerate(zip(x,y)): #x dan y itu ada 5 SPL di soal, makanya di looping
            #urutan angka idx dari enumerate
            #zip(x,y) nyatuin elemen x dan y
            #matrix x itu matrix_A
            #matrix y itu matrix_B
        print(f"matrixA (Koefisien):\n {np.array(matrix_A)}")
        print(f"matrixB (hasil):\n {np.array(matrix_B)}")
        
        gauss_seidel(matrix_A, matrix_B)
        
        
        print("\n")
        


In [3]:
main()


matrixA (Koefisien):
 [[-61  11   7]
 [ 20  67   8]
 [ 38  16 -98]]
matrixB (hasil):
 [-969   79 -265]
Matrix diag:
[61 67 98]

Matrix total offDiag:
[18 28 54]
Solusi x iterasi ke 0
[15.8852459  -3.56275997  8.28199168]
Solusi x iterasi ke 1
[16.19317348 -4.64357318  8.22493287]
Solusi x iterasi ke 2
[15.991725   -4.57662631  8.1577503 ]
Solusi x iterasi ke 3
[15.99608791 -4.56990687  8.16053909]
Sudah Konvergen


matrixA (Koefisien):
 [[-109   14   57]
 [   2  -64   24]
 [  38    4  -85]]
matrixB (hasil):
 [  78   -1 -382]
Matrix diag:
[109  64  85]

Matrix total offDiag:
[71 26 42]
Solusi x iterasi ke 0
[-0.71559633 -0.00673739  4.17388694]
Solusi x iterasi ke 1
[1.46621314 1.62665176 5.22614949]
Solusi x iterasi ke 2
[2.22627198 2.04500206 5.58562757]
Solusi x iterasi ke 3
[2.46798899 2.18735999 5.70038849]
Solusi x iterasi ke 4
[2.54628609 2.23284212 5.73753223]
Sudah Konvergen


matrixA (Koefisien):
 [[-62   3  13]
 [ 17 -93  39]
 [ 20   8 -69]]
matrixB (hasil):
 [-970 -849 -449]