In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# ukuran pasti n * n sama
x = [
    [
        [95, 12, -8],
        [7, -88, 14],
        [5, 9, -102]
    ],
    [
        [120, -15, 10],
        [8, -110, 6],
        [12, 7, -98]
    ],
    [
        [-105, 18, 9],
        [6, -92, 11],
        [10, 5, -115]
    ],
    [
        [85, -6, 4],
        [3, 97, 8],
        [7, 2, 90]
    ],
    [
        [-130, 25, 12],
        [14, -140, 20],
        [18, 10, -150]
    ]
]

y = [
    [210, -340, 415],
    [-520, 630, -710],
    [305, -450, 520],
    [150, 275, 390],
    [-610, 720, -830]
]


In [14]:
# Cek apakah dia diagonally dominance
def is_not_diagonally_dominance(A):
    diag = np.diag(np.abs(A))
    off_diag = np.sum(np.abs(A), axis=1) - diag
    
    if np.all(diag > off_diag):
        return False
    else:
        return True

In [15]:
def gauss_seidel(matrix_A, matrix_B, max_iters = 53, tolerance = 0.093):
    
    xs = np.array(matrix_A)
    ys = np.array(matrix_B)
    
    if (is_not_diagonally_dominance(xs)):
        print("Tidak diagonally dominance")
        return
    
    diag = np.diag(xs)
    xs = -xs
    np.fill_diagonal(xs, 0)
    
    x_old = np.zeros(xs.shape[0])
    
    for iter in range(max_iters):
        
        x_new = np.array(x_old)
        
        for j, row in enumerate(xs):
            x_new[j] = (ys[j] + np.dot(x_new, row)) / diag[j]
            
        print(x_new)
        
        error = np.sqrt(np.sum((x_new - x_old)**2))
        
        if (error < tolerance):
            print("convergent")
            return
        
        x_old = x_new
        

In [16]:
def main():
    for idx, (matrix_A, matrix_B) in enumerate(zip(x,y)):
        
        gauss_seidel(matrix_A, matrix_B)
        

main()

[ 2.21052632  4.03947368 -3.60384417]
[ 1.39679539  3.40140624 -3.70003301]
[ 1.46929327  3.39187035 -3.69732059]
convergent
[-4.33333333 -6.04242424  6.28268398]
[-5.61219336 -5.79274039  6.14392344]
[-5.5694195  -5.79719832  6.14884263]
convergent
[-2.9047619   4.70186335 -4.56989828]
[-2.49043375  4.18248387 -4.55645146]
[-2.57831765  4.17836009 -4.56427284]
convergent
[1.76470588 2.78047301 4.13429014]
[1.76641974 2.43944763 4.14173518]
[1.741997   2.43958894 4.14363159]
convergent
[ 4.69230769 -4.67362637  5.78483516]
[ 4.32751817 -3.8837003   5.79372216]
[ 4.48024737 -3.86715781  5.8131525 ]
[ 4.48522219 -3.86388457  5.81396769]
convergent
